<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td>
                <h3 class="icon-head head-blog">
                    <?php echo Mage::helper('stuntcoders_fbproductfeed')->__('Manage Facebook Product Feed'); ?>
                </h3>
            </td>
            <td class="a-right">
                <?php echo $this->getChildHtml('fbproductfeed.back'); ?>
                <?php echo $this->getChildHtml('fbproductfeed.delete'); ?>
                <?php echo $this->getChildHtml('fbproductfeed.savenew'); ?>
                <?php echo $this->getChildHtml('fbproductfeed.generate'); ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getLayout()->createBlock('stuntcoders_fbproductfeed/add_form')->toHtml(); ?>
